apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    'helm.sh/hook': pre-install
    'helm.sh/hook-weight': '-5'
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-api'
  name: 'storage-{{.Release.Name}}-saleor-media'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    'helm.sh/hook': pre-install
    'helm.sh/hook-weight': '-5'
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-api'
  name: 'storage-{{.Release.Name}}-saleor-static'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
